AllCops:
  TargetRubyVersion: 3.0.1
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "test/**/*"
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Exclude:
    - 'db/**/*'